print("Calculate the area of a wall.")
width = int(input("Enter the width in meters: "))
height = int(input("Enter the height in meters: "))
print(f"Width is {width} m and height is {height} m.")
print(f"The wall will be {width*height} square meters.")
