Num1 = 47
Num2 = 102
Sum = Num1 + Num2
Diff = Num2 - Num1
Product = Sum * Diff
print(f"{Num1} + {Num2} = {Sum}")
print(f"{Num2} - {Num1} = {Diff}")
print(f"{Sum} * {Diff} = {Product}")
print(f"( {Num1} + {Num2} ) * ( {Num2} - {Num1} ) = {Product}")
